version: "3"
services:
  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  docker:
    image: docker:dind   #to execute docker command in jenkins
    container_name: jenkins-docker  
    privileged: true
    command: --storage-driver=overlay2  
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins_data:/var/jenkins_home"
    ports:
      - "2376:2376"
    networks:
      - net    
  jenkins:
    image: myjenkins-blueocean:2.401.1-1
    build:
      context: .
      dockerfile: jenkins-Dockerfile
    privileged: true  
    #user: root  
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-blueocean
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1   
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"  
      - "jenkins-docker-certs:/certs/client:ro"  
    networks:
      - net    
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"   
  remote_host:
    container_name: remote-host
    image: remote-host
    volumes:
      - "$PWD/remote_host:/tmp"  
    build:
      context: .
      dockerfile: remote-host-Dockerfile
    networks:
      - net
  db_host:
    image: mysql:5.7
    container_name: mysql
    networks:
      - net
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - net
      

networks:
  net:
volumes:                    #named volume must declare.
  nexus-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins_data:
  jenkins-docker-certs:
